name: 'giantnodes/semver'
description: 'increments the semver from a version file'
author: 'PHILLIPS71'

inputs:
  path:
    description: 'a path to a version file that contains the version to increment'
    required: true
  type:
    type: choice
    description: 'a sermver release type'
    default: 'prerelease'
    required: true
    options:
      - prerelease
      - prepatch
      - patch
      - preminor
      - minor
      - premajor
      - major
  identifier:
    required: false
    description: 'a identifier to be used to prefix version increment'

outputs:
  version:
    description: 'the incremented version'

runs:
  using: node20
  main: dist/index.js
