name: 'ðŸ·ï¸  '

inputs:
  GITHUB_TOKEN:
    required: true
  RELEASE_TYPE:
    required: true
  RELEASE_IDENTIFIER:
    required: false

outputs:
  version:
    value: ${{ steps.version.outputs.version }}
  tag:
    value: ${{ steps.version.outputs.tag }}
  branch:
    value: ${{ steps.branch.outputs.branch }}

runs:
  using: 'composite'
  steps:
    - name: 'ðŸ·ï¸  Increment Release'
      id: version
      uses: ./
      with:
        path: VERSION.txt
        type: ${{ inputs.RELEASE_TYPE }}
        identifier: ${{ inputs.RELEASE_IDENTIFIER }}

    - name: 'ðŸ·ï¸  Version @giantnodes/next-semver'
      shell: bash
      run: |
        pnpm version ${{ steps.version.outputs.version }} --no-git-tag-version

    - name: 'ðŸ·ï¸  Configure Git'
      shell: bash
      run: |
        git config --global user.name 'giantnodes-bot'
        git config --global user.email 'bot@giantnodes.com'

    - name: 'ðŸ·ï¸  Tag, Commit & Release'
      shell: bash
      id: branch
      run: |
        git checkout -b release/${{ steps.version.outputs.version }}
        git commit -anm 'chore(release): v${{ steps.version.outputs.version }}'
        git push origin release/${{ steps.version.outputs.version }}

        gh release create v${{ steps.version.outputs.version }} ${{ steps.version.outputs.tag == 'latest' && '--latest' || '--prerelease' }} --generate-notes

        echo "branch=$(git branch --show-current)" >> $GITHUB_OUTPUT
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
